/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EmberRouteImport } from './routes/ember'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FastingRouteImport } from './routes/fasting'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as EssaysIndexRouteImport } from './routes/essays.index'
import { Route as EssaysSlugRouteImport } from './routes/essays.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EmberRoute = EmberRouteImport.update({
  id: '/ember',
  path: '/ember',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FastingRoute = FastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIndexRoute = EssaysIndexRouteImport.update({
  id: '/essays/',
  path: '/essays/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysSlugRoute = EssaysSlugRouteImport.update({
  id: '/essays/$slug',
  path: '/essays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ember': typeof EmberRoute
  '/faq': typeof FaqRoute
  '/fasting': typeof FastingRoute
  '/shop': typeof ShopRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ember': typeof EmberRoute
  '/faq': typeof FaqRoute
  '/fasting': typeof FastingRoute
  '/shop': typeof ShopRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/essays': typeof EssaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ember': typeof EmberRoute
  '/faq': typeof FaqRoute
  '/fasting': typeof FastingRoute
  '/shop': typeof ShopRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ember'
    | '/faq'
    | '/fasting'
    | '/shop'
    | '/essays/$slug'
    | '/essays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ember'
    | '/faq'
    | '/fasting'
    | '/shop'
    | '/essays/$slug'
    | '/essays'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ember'
    | '/faq'
    | '/fasting'
    | '/shop'
    | '/essays/$slug'
    | '/essays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmberRoute: typeof EmberRoute
  FaqRoute: typeof FaqRoute
  FastingRoute: typeof FastingRoute
  ShopRoute: typeof ShopRoute
  EssaysSlugRoute: typeof EssaysSlugRoute
  EssaysIndexRoute: typeof EssaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ember': {
      id: '/ember'
      path: '/ember'
      fullPath: '/ember'
      preLoaderRoute: typeof EmberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasting': {
      id: '/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof FastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/': {
      id: '/essays/'
      path: '/essays'
      fullPath: '/essays/'
      preLoaderRoute: typeof EssaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$slug': {
      id: '/essays/$slug'
      path: '/essays/$slug'
      fullPath: '/essays/$slug'
      preLoaderRoute: typeof EssaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmberRoute: EmberRoute,
  FaqRoute: FaqRoute,
  FastingRoute: FastingRoute,
  ShopRoute: ShopRoute,
  EssaysSlugRoute: EssaysSlugRoute,
  EssaysIndexRoute: EssaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
